version: 2.10
orbs:
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: cimg/node:16.14.0

    steps:
      - checkout
      - run: node --version
      - run: npm install
      - snyk/scan:
          fail-on-issues: false
